# Generated by Django 4.0.5 on 2022-06-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=25, null=True)),
                ('modele', models.CharField(blank=True, max_length=25, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_location', to='flotte.vehicule')),
            ],
        ),
    ]
