# Generated by Django 4.0.5 on 2022-06-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_user_password_alter_user_username_visite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeport',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passeport_personnel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permis',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permis_personnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
