# Generated by Django 4.0.5 on 2022-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F_CREGLEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_no', models.IntegerField(blank=True, null=True)),
                ('ct_num_payeur', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_ct_num_payeur', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_date', models.DateField(blank=True, null=True)),
                ('rg_reference', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_libelle', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_montant', models.FloatField(blank=True, null=True)),
                ('rg_montant_dev', models.FloatField(blank=True, null=True)),
                ('n_reglement', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_impute', models.IntegerField(blank=True, null=True)),
                ('rg_compta', models.IntegerField(blank=True, null=True)),
                ('ec_no', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_type', models.IntegerField(blank=True, null=True)),
                ('rg_cours', models.IntegerField(blank=True, null=True)),
                ('n_devise', models.IntegerField(blank=True, null=True)),
                ('jo_num', models.CharField(blank=True, max_length=25, null=True)),
                ('cg_num_cont', models.CharField(blank=True, max_length=255, null=True)),
                ('rg_impaye', models.DateField(blank=True, null=True)),
                ('cg_num', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_type_reg', models.IntegerField(blank=True, null=True)),
                ('rg_heure', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_piece', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_banque', models.IntegerField(blank=True, null=True)),
                ('ct_num_payeur_orig', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_date_ech_cont', models.DateField(blank=True, null=True)),
                ('cg_num_ecart', models.CharField(blank=True, max_length=25, null=True)),
                ('jo_num_ecart', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_montant_ecart', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_DOCENTETE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_domaine', models.CharField(blank=True, max_length=25, null=True)),
                ('do_type', models.CharField(blank=True, max_length=25, null=True)),
                ('do_piece', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_do_piece', models.CharField(blank=True, max_length=25, null=True)),
                ('do_date', models.DateField(blank=True, null=True)),
                ('do_ref', models.CharField(blank=True, max_length=25, null=True)),
                ('do_tiers', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_do_tiers', models.CharField(blank=True, max_length=25, null=True)),
                ('co_no', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_co_no', models.CharField(blank=True, max_length=25, null=True)),
                ('do_period', models.CharField(blank=True, max_length=25, null=True)),
                ('do_devise', models.CharField(blank=True, max_length=25, null=True)),
                ('do_cours', models.CharField(blank=True, max_length=25, null=True)),
                ('de_no', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_de_no', models.CharField(blank=True, max_length=25, null=True)),
                ('li_no', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_li_no', models.CharField(blank=True, max_length=25, null=True)),
                ('cb_ct_num_payeur', models.CharField(blank=True, max_length=25, null=True)),
                ('do_exp_edit', models.CharField(blank=True, max_length=25, null=True)),
                ('do_nb_facture', models.CharField(blank=True, max_length=25, null=True)),
                ('do_bl_facture', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_DOCREGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_no', models.CharField(blank=True, max_length=25, null=True)),
                ('do_domaine', models.CharField(blank=True, max_length=25, null=True)),
                ('do_type', models.CharField(blank=True, max_length=25, null=True)),
                ('do_piece', models.CharField(blank=True, max_length=25, null=True)),
                ('dr_type_regl', models.CharField(blank=True, max_length=25, null=True)),
                ('dr_date', models.DateField(blank=True, null=True)),
                ('dr_libelle', models.CharField(blank=True, max_length=25, null=True)),
                ('dr_pourcent', models.FloatField(blank=True, null=True)),
                ('dr_montant', models.FloatField(blank=True, null=True)),
                ('dr_montant_dev', models.FloatField(blank=True, null=True)),
                ('dr_equil', models.CharField(blank=True, max_length=25, null=True)),
                ('ec_no', models.IntegerField(blank=True, null=True)),
                ('dr_regle', models.CharField(blank=True, max_length=25, null=True)),
                ('n_reglement', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='F_REGLECH',
            fields=[
                ('rg_no', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dr_no', models.CharField(blank=True, max_length=25, null=True)),
                ('do_domaine', models.CharField(blank=True, max_length=25, null=True)),
                ('do_type', models.CharField(blank=True, max_length=25, null=True)),
                ('do_piece', models.CharField(blank=True, max_length=25, null=True)),
                ('rc_montant', models.CharField(blank=True, max_length=25, null=True)),
                ('rg_type_reg', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
