# Generated by Django 4.0.5 on 2022-06-06 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('immatriculation', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('num_serie', models.CharField(blank=True, max_length=25, null=True)),
                ('kilometrage', models.IntegerField(blank=True, null=True)),
                ('engin', models.CharField(blank=True, max_length=25, null=True)),
                ('consommation', models.CharField(blank=True, max_length=25, null=True)),
                ('entretien', models.CharField(blank=True, max_length=25, null=True)),
                ('constructeur', models.CharField(blank=True, max_length=25, null=True)),
                ('type_commercial', models.CharField(blank=True, max_length=25, null=True)),
                ('activite', models.CharField(blank=True, max_length=25, null=True)),
                ('genre', models.CharField(blank=True, max_length=25, null=True)),
                ('type_constructeur', models.CharField(blank=True, max_length=25, null=True)),
                ('date_pmc', models.DateField(blank=True, null=True)),
                ('carrosserie', models.CharField(blank=True, max_length=25, null=True)),
                ('energie', models.CharField(blank=True, max_length=25, null=True)),
                ('puissance_fiscale', models.IntegerField(blank=True, null=True)),
                ('nombre_essieux', models.IntegerField(blank=True, null=True)),
                ('charge_utile', models.IntegerField(blank=True, null=True)),
                ('poids_vide', models.IntegerField(blank=True, null=True)),
                ('ptac_ptra', models.IntegerField(blank=True, null=True)),
                ('nombre_places', models.IntegerField(blank=True, null=True)),
                ('nombre_debout', models.IntegerField(blank=True, null=True)),
                ('cylidree', models.IntegerField(blank=True, null=True)),
                ('a_louer', models.BooleanField(blank=True, null=True)),
                ('affecte', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=25, null=True)),
                ('modele', models.CharField(blank=True, max_length=25, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_contrat_location', to='flotte.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='ContratAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendeur', models.CharField(blank=True, max_length=25, null=True)),
                ('marque', models.CharField(blank=True, max_length=25, null=True)),
                ('modele', models.CharField(blank=True, max_length=25, null=True)),
                ('chassis', models.CharField(blank=True, max_length=25, null=True)),
                ('moteur', models.CharField(blank=True, max_length=25, null=True)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_contrat_achat', to='flotte.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('kilometrage', models.IntegerField(blank=True, null=True)),
                ('consommation_totale', models.IntegerField(blank=True, null=True)),
                ('consommation', models.IntegerField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_consommation', to='flotte.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etat', models.BooleanField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_affectation', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_affectation', to='flotte.vehicule')),
            ],
        ),
    ]
