# Generated by Django 4.0.5 on 2022-06-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flotte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='chauffeur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_affectation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='vehicule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_affectation', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='vehicule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_contrat_achat', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='vehicule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_contrat_location', to='flotte.vehicule'),
        ),
    ]
