# Generated by Django 4.0.5 on 2022-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0002_alter_affectation_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='a_louer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='affecte',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
