# Generated by Django 4.0.5 on 2022-06-07 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flotte', '0003_alter_vehicule_a_louer_alter_vehicule_affecte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_affectation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='etat',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicule_affectation', to='flotte.vehicule'),
        ),
    ]
