# Generated by Django 4.0.5 on 2022-06-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0004_alter_affectation_chauffeur_alter_affectation_etat_and_more'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeinterventiongarage',
            name='date_demande',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandeinterventiongarage',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demandeinterventiongarage',
            name='etat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandeinterventiongarage',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demandeinterventiongarage',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_vehicule_garage', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='collaborateur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='entreprise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='montant_mo_ht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='montant_pieces_ht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='montant_total_ht',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='objet',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='interventiongarage',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_vehicule_garage', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='categorie',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='code_casier',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='famille',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='nom',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='nombre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piecerechangegarage',
            name='unite',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planentretiengarage',
            name='frequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planentretiengarage',
            name='operation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planentretiengarage',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planentretiengarage',
            name='unite',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planentretiengarage',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_vehicule_garage', to='flotte.vehicule'),
        ),
    ]
