# Generated by Django 4.0.5 on 2022-06-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(blank=True, max_length=25, null=True)),
                ('intitule', models.CharField(blank=True, max_length=25, null=True)),
                ('abrege', models.CharField(blank=True, max_length=25, null=True)),
                ('compte_collectif', models.CharField(blank=True, max_length=25, null=True)),
                ('qualite', models.CharField(blank=True, max_length=25, null=True)),
                ('interlocuteur', models.CharField(blank=True, max_length=25, null=True)),
                ('commentaire', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('civilite', models.CharField(blank=True, max_length=25, null=True)),
                ('nom', models.CharField(blank=True, max_length=25, null=True)),
                ('prenom', models.CharField(blank=True, max_length=25, null=True)),
                ('service', models.CharField(blank=True, max_length=25, null=True)),
                ('fonction', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('portable', models.CharField(blank=True, max_length=25, null=True)),
                ('telecopie', models.CharField(blank=True, max_length=25, null=True)),
                ('skype', models.CharField(blank=True, max_length=25, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=25, null=True)),
                ('facebook', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_tiers', to='tiers.tiers')),
            ],
        ),
    ]
